spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EmailSender
    username:
    password:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: create-drop
    packagesToScan:
      - com.example.demo.model
  flyway:
    locations: "classpath:/db.migration"

flyway:
  validate-on-migrate: false
  encoding: UTF8MB4
  out-of-order: true